# Generated by Django 3.1.7 on 2021-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptid',
            name='image',
            field=models.ImageField(default="", upload_to='cryptidImages'),
            preserve_default=False,
        ),
    ]
