# Generated by Django 3.1.7 on 2021-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0004_auto_20210318_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptid',
            name='image',
            field=models.ImageField(upload_to='cryptids/'),
        ),
    ]
