# Generated by Django 3.1.7 on 2021-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0005_auto_20210318_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='cryptid',
        ),
        migrations.RemoveField(
            model_name='location',
            name='discoveryDate',
        ),
        migrations.AddField(
            model_name='cryptid',
            name='discovery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='cryptids',
            field=models.ManyToManyField(related_name='locations', to='cage.Cryptid'),
        ),
    ]
